### ISSUE TITLE
Critical error: Duplicate Key

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-view-renderer#127]
### What do you get instead? 

![image](https://github.com/user-attachments/assets/53d5c491-ce4a-4068-b6d8-89fb623e86d6)

With stack trace: 

ErrorException: Duplicate key "yiisoft/yii-view-renderer => viewPath" in the following configs while building "params-web" group:
 - vendor/yiisoft/yii-view-renderer/config/params.php
 - vendor/yiisoft/yii-view/config/params.php in C:\wamp64\www\invoice\vendor\yiisoft\config\src\Merger.php:272
Stack trace:
#0 C:\wamp64\www\invoice\vendor\yiisoft\config\src\Merger.php(146): Yiisoft\Config\Merger->throwDuplicateKeyErrorException('params-web', Array, Array)
#1 C:\wamp64\www\invoice\vendor\yiisoft\config\src\Merger.php(123): Yiisoft\Config\Merger->performMerge(Object(Yiisoft\Config\Context), Array, Array, Array, NULL, false, 1)
#2 C:\wamp64\www\invoice\vendor\yiisoft\config\src\Merger.php(65): Yiisoft\Config\Merger->performMerge(Object(Yiisoft\Config\Context), Array, Array, Array, NULL, false)
#3 C:\wamp64\www\invoice\vendor\yiisoft\config\src\Config.php(111): Yiisoft\Config\Merger->merge(Object(Yiisoft\Config\Context), Array, Array)
#4 C:\wamp64\www\invoice\vendor\yiisoft\config\src\Config.php(109): Yiisoft\Config\Config->buildGroup('params', Array, 'params-web')
#5 C:\wamp64\www\invoice\vendor\yiisoft\config\src\Config.php(92): Yiisoft\Config\Config->buildGroup('params-web')
#6 C:\wamp64\www\invoice\vendor\yiisoft\config\src\Config.php(72): Yiisoft\Config\Config->runBuildParams()
#7 C:\wamp64\www\invoice\vendor\yiisoft\yii-runner\src\ApplicationRunner.php(156): Yiisoft\Config\Config->get('di-web')
#8 C:\wamp64\www\invoice\vendor\yiisoft\yii-runner\src\ApplicationRunner.php(189): Yiisoft\Yii\Runner\ApplicationRunner->getConfiguration('di-web')
#9 C:\wamp64\www\invoice\vendor\yiisoft\yii-runner\src\ApplicationRunner.php(144): Yiisoft\Yii\Runner\ApplicationRunner->createDefaultContainer()
#10 C:\wamp64\www\invoice\vendor\yiisoft\yii-runner-http\src\HttpApplicationRunner.php(131): Yiisoft\Yii\Runner\ApplicationRunner->getContainer()
#11 C:\wamp64\www\invoice\public\index.php(43): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#12 {main}

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.2
| Operating system | Windows 11

**Comment by vjik** [comment]
`yiisoft/yii-view-renderer` is new name for `yiisoft/yii-view`. Remove `yiisoft/yii-view` from your app.

**Comment by rossaddison** [comment]
Thanks. Just tested it without yiisoft/yii-view.
