### ISSUE TITLE
Dependency Checker: The following 5 unknown symbols were found

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-view-renderer#128]
### Additional info

![image](https://github.com/user-attachments/assets/09a00429-3a74-4321-9a06-80790b99c519)

https://github.com/rossaddison/invoice/actions/runs/10851718209/job/30116097026#step:8:21

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.2
| Operating system | Windows 11

**Comment by vjik** [comment]
You use classes from transitive dependency. Add `yiisoft/yii-view-renderer` to your composer.json.

**Comment by rossaddison** [comment]
Sorry Vjik. Careless error. Must have deleted it with yiisoft/yii-view.
