### ISSUE TITLE
Replace deprecated CsrfMiddleware to actual CsrfTokenMiddleware in CsrfViewInjection

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/yii-view-renderer#133]
https://github.com/yiisoft/yii-view-renderer/blob/8ff704ae17acb542002ea42a67a893b8ea42b220/src/CsrfViewInjection.php#L23

**Comment by vjik** [comment]
Done by https://github.com/yiisoft/yii-view-renderer/pull/135
